#=============================================
# The code runs TARC simulation with run.mac
#=============================================

: ${1?"Usage: $0 <macroname: run.mac | vis.mac"}

unset G4NEUTRONHP_SKIP_MISSING_ISOTOPES 
unset G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE
unset G4NEUTRONHP_USE_ONLY_PHOTONEVAPORATION
unset G4NEUTRONHP_NELECT_DOPPLER
unset G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS
unset G4CASCADE_USE_PRECOMPOUND  

# export PHYSLIST="FTFP_BERT"
# export PHYSLIST="FTFP_BERT_HP"
# export PHYSLIST="QBBC"
# export PHYSLIST="QGSP_BERT_HP"
# export PHYSLIST="QGSP_INCLXX_HP"

export G4NEUTRONHP_PRODUCE_FISSION_FRAGMENTS=1
export G4NEUTRONHP_SKIP_MISSING_ISOTOPES=1 
export G4NEUTRONHP_NELECT_DOPPLER=1
export AllowForHeavyElements=1
export G4NEUTRONHP_DO_NOT_ADJUST_FINAL_STATE=1
#export G4CASCADE_USE_PRECOMPOUND=1    # if set switches off Doppler

export PHYSLIST="QGSP_BIC_HP"
#export dateStr="histo"_`date +%d_%m_%Y`
#mkdir -p $dateStr

./tarcVega Data/GeomData/tarc_geometry.gdml -m $1
