#=============================================
# The code runs TARC simulation with run.mac
#=============================================

# export PHYSLIST="FTFP_BERT"
# export PHYSLIST="FTFP_BERT_HP"
# export PHYSLIST="QBBC"
# export PHYSLIST="QGSP_BERT_HP"
# export PHYSLIST="QGSP_INCLXX_HP"

export PHYSLIST="QGSP_BIC_HP"
export dateStr=`date +%d_%m_%Y`
mkdir -p $dateStr

./tarcVega GeomData/tarc_geometry.gdml -m run.mac
